# Generated by Django 5.2 on 2025-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='work_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
