# Generated by Django 5.2 on 2025-05-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0002_resume_work_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
