# Generated by Django 5.2 on 2025-05-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0003_resume_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='jobs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
