# Generated by Django 5.2 on 2025-05-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0004_resume_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='recommendation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
