# Generated by Django 5.2 on 2025-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0005_resume_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resources_recommended',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
