# Generated by Django 5.2 on 2025-05-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0006_resume_resources_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='jobs',
            new_name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resources_recommended',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_field',
        ),
    ]
