# Generated by Django 5.2 on 2025-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0007_rename_jobs_resume_extracted_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title_s', models.CharField(blank=True, max_length=200, null=True)),
                ('hard_skills', models.JSONField(blank=True, null=True)),
                ('soft_skills', models.JSONField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('entry_level', 'Entry Level'), ('intern', 'Intern'), ('trainee', 'Trainee'), ('associate', 'Associate'), ('junior', 'Junior'), ('beginner', 'Beginner'), ('mid_level', 'Mid Level'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced'), ('senior', 'Senior'), ('lead', 'Lead'), ('principal', 'Principal'), ('staff', 'Staff'), ('senior_staff', 'Senior Staff'), ('architect', 'Architect'), ('senior_architect', 'Senior Architect'), ('team_lead', 'Team Lead'), ('tech_lead', 'Tech Lead'), ('manager', 'Manager'), ('senior_manager', 'Senior Manager'), ('director', 'Director'), ('senior_director', 'Senior Director'), ('vp', 'Vice President'), ('svp', 'Senior Vice President'), ('cto', 'Chief Technology Officer'), ('ceo', 'Chief Executive Officer'), ('consultant', 'Consultant'), ('senior_consultant', 'Senior Consultant'), ('specialist', 'Specialist'), ('expert', 'Expert'), ('freelancer', 'Freelancer'), ('contractor', 'Contractor')], max_length=30, null=True)),
                ('preferred_location', models.JSONField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
