# Generated by Django 5.2 on 2025-05-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0009_manualresume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualresume',
            name='jobs_matched',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='jobs_matched',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
