# Generated by Django 5.2 on 2025-05-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0010_manualresume_jobs_matched_resume_jobs_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='recommendation_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
