# Generated by Django 5.2 on 2025-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyJobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('required_education', models.JSONField(blank=True, default=dict)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company Job Listing',
                'verbose_name_plural': 'Company Job Listings',
            },
        ),
    ]
