"""
Django settings for Core project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from Core.secrets.parameter_store import *
from pathlib import Path
import os
import logging
from dotenv import load_dotenv
from decouple import config
from botocore.exceptions import ClientError

# Set up logging
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

parameter_store = ParameterStoreClient()

# Database Configuration
try:
    parameter_store_credentials = parameter_store.get_parameters([
        '/atp-project/django/DATABASE_NAME',
        '/atp-project/django/DB_USER',
        '/atp-project/django/AWS_HOST',
        '/atp-project/django/db_password',
    ])

    db_name = parameter_store_credentials.get('/atp-project/django/DATABASE_NAME')
    db_user = parameter_store_credentials.get('/atp-project/django/DB_USER')
    db_host = parameter_store_credentials.get('/atp-project/django/AWS_HOST')
    db_password = parameter_store_credentials.get('/atp-project/django/db_password')

    # Validate that all required parameters were retrieved
    if not all([db_name, db_user, db_host, db_password]):
        missing = [param for param, value in {
            'DATABASE_NAME': db_name,
            'DB_USER': db_user,
            'AWS_HOST': db_host,
            'db_password': db_password
        }.items() if not value]
        raise ValueError(f"Missing required parameters: {missing}")

    print("Database credentials obtained successfully!")

    # Database configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': '5432',
        }
    }

except Exception as e:
    print(f"Failed to obtain database credentials: {e}")
    logger.error(f"Database configuration error: {e}")

    # Fallback database configuration (for development/testing)
    # Remove this in production or ensure it's properly secured
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = True

# Django Configuration Parameters according to Amazon Q
try:
    parameter_store_credentials = parameter_store.get_parameters([
        '/atp-project/django/DJANGO_SECRET_KEY',
        '/atp-project/django/ALLOWED_HOSTS',
        '/atp-project/django/PRIVATE_IP',
        '/atp-project/django/PUBLIC_DNS',
    ])

    SECRET_KEY = parameter_store_credentials.get('/atp-project/django/DJANGO_SECRET_KEY')
    host = parameter_store_credentials.get('/atp-project/django/ALLOWED_HOSTS')
    private_ip = parameter_store_credentials.get('/atp-project/django/PRIVATE_IP')  
    public_dns = parameter_store_credentials.get('/atp-project/django/PUBLIC_DNS')  


    ALLOWED_HOSTS = [
        private_ip,
        public_dns,
        host,
        'localhost',
        '127.0.0.1',
        'www.resume-analyzer.net',
        'resume-analyzer.net'
    ]


    if not SECRET_KEY:
        raise ValueError("DJANGO_SECRET_KEY not found in parameter store")

except Exception as e:
    logger.error(f"Configuration parameter error: {e}")
    # For production, you should fail here instead of using a default
    SECRET_KEY = 'your-fallback-secret-key-for-development-only'
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        'www.resume-analyzer.net',
        'resume-analyzer.net',
        '3.220.71.84'
    ]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'UserInterface',
    'UserAuth',
    'Scanner',
    'Evaluator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Core.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Add this for debugging
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom error handlers
handler400 = 'UserInterface.views.bad_request'
handler403 = 'UserInterface.views.permission_denied'
handler404 = 'UserInterface.views.page_not_found'
handler500 = 'UserInterface.views.server_error'

# SSL Settings
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'




try:
    parameter_store_credentials = parameter_store.get_parameters([
        '/atp-project/django/EMAIL_HOST_USER',
        '/atp-project/django/GOOGLE_HOST_PASSWORD',
    ])

    EMAIL_HOST_USER = parameter_store_credentials.get('/atp-project/django/EMAIL_HOST_USER')
    GOOGLE_HOST_PASSWORD = parameter_store_credentials.get('/atp-project/django/GOOGLE_HOST_PASSWORD')

    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = EMAIL_HOST_USER
    EMAIL_HOST_PASSWORD = GOOGLE_HOST_PASSWORD
    DEFAULT_FROM_EMAIL = 'admin@resume-analyzer.net'

except Exception as e:
    logger.error(e)



# Password Reset Configuration
PASSWORD_RESET_TIMEOUT_MINUTES = 60
AUTO_LOGIN_AFTER_PASSWORD_RESET = True

# Site Configuration
SITE_NAME = os.getenv('SITE_NAME', 'Resume Analyzer')
SITE_URL = os.getenv('SITE_URL', 'https://resume-analyzer.net')

# Security Settings
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Session Security
SESSION_COOKIE_HTTPONLY = True  
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/home/ec2-user/ATP-PROJECT/django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}