# Generated by Django 5.2 on 2025-04-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume_limit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
