# Generated by Django 5.2 on 2025-04-30 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_alter_userprofile_resume_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume_limit',
            field=models.IntegerField(default=3, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
