# Generated by Django 5.2 on 2025-05-12 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0006_alter_userprofile_resume_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume_limit',
            field=models.IntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
