# Generated by Django 5.2 on 2025-04-28 16:40

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('UserInterface', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE "UserInterface_feedback" 
            ADD COLUMN "submitted" BOOLEAN DEFAULT FALSE;
            """,
            reverse_sql="""
            ALTER TABLE "UserInterface_feedback"
            DROP COLUMN "submitted";
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE "UserInterface_feedback"
            ALTER COLUMN "created_at" TYPE timestamp with time zone
            USING (TIMESTAMP '2000-01-01' + "created_at");
            """,
            reverse_sql="""
            ALTER TABLE "UserInterface_feedback"
            ALTER COLUMN "created_at" TYPE time without time zone
            USING "created_at"::time without time zone;
            """
        )

    ]