# Generated by Django 5.2 on 2025-04-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0002_feedback_submitted_alter_feedback_created_at'),
        ('UserInterface', '0003_auto_20250428_1640'),
    ]

    operations = [
    ]
