# Generated by Django 5.2 on 2025-04-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0004_merge_20250428_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='submitted',
        ),
    ]
