#  Career Fields List
# AI Generated this long ass list
CAREER_FIELDS = [
    # Core Technology Fields
    ("technology", "Technology & IT"),
    ("software_engineering", "Software Engineering"),
    ("data_science", "Data Science & Analytics"),
    ("cybersecurity", "Cybersecurity"),
    ("devops", "DevOps & Infrastructure"),
    ("ai_ml", "Artificial Intelligence & Machine Learning"),
    ("cloud_computing", "Cloud Computing"),
    ("networking", "Networking & Telecommunications"),
    ("tech_support", "IT Support & Helpdesk"),
    ("blockchain", "Blockchain & Web3"),
    ("mobile_development", "Mobile App Development"),
    ("web_development", "Web Development"),
    ("database_admin", "Database Administration"),
    ("systems_analysis", "Systems Analysis"),
    ("quality_assurance", "Software Testing & QA"),
    ("product_management_tech", "Technical Product Management"),
    ("robotics", "Robotics & Automation"),
    ("embedded_systems", "Embedded Systems"),
    ("information_systems", "Information Systems"),
    ("computer_hardware", "Computer Hardware Engineering"),

    # Healthcare & Medical
    ("healthcare", "Healthcare & Medical"),
    ("nursing", "Nursing"),
    ("mental_health", "Mental Health & Counseling"),
    ("pharmacy", "Pharmacy"),
    ("dental", "Dental"),
    ("medical_technology", "Medical Lab & Imaging Tech"),
    ("public_health", "Public Health"),
    ("veterinary", "Veterinary Medicine"),
    ("physical_therapy", "Physical Therapy"),
    ("occupational_therapy", "Occupational Therapy"),
    ("speech_therapy", "Speech-Language Pathology"),
    ("respiratory_therapy", "Respiratory Therapy"),
    ("radiology", "Radiology & Medical Imaging"),
    ("emergency_medical", "Emergency Medical Services"),
    ("medical_research", "Medical Research"),
    ("healthcare_admin", "Healthcare Administration"),
    ("nutrition", "Nutrition & Dietetics"),
    ("optometry", "Optometry"),
    ("chiropractic", "Chiropractic Medicine"),
    ("medical_assistant", "Medical Assistant"),
    ("home_health", "Home Healthcare"),
    ("laboratory_science", "Clinical Laboratory Science"),

    # Finance & Business
    ("finance", "Finance & Banking"),
    ("accounting", "Accounting"),
    ("investment", "Investment & Asset Management"),
    ("insurance", "Insurance"),
    ("real_estate", "Real Estate"),
    ("business", "Business & Management"),
    ("consulting", "Consulting"),
    ("entrepreneurship", "Entrepreneurship"),
    ("project_management", "Project Management"),
    ("human_resources", "Human Resources (HR)"),
    ("operations", "Operations & Supply Chain"),
    ("business_analysis", "Business Analysis"),
    ("financial_planning", "Financial Planning & Advisory"),
    ("corporate_finance", "Corporate Finance"),
    ("risk_management", "Risk Management"),
    ("compliance", "Compliance & Regulatory Affairs"),
    ("audit", "Internal Audit"),
    ("treasury", "Treasury Management"),
    ("procurement", "Procurement & Purchasing"),
    ("logistics", "Logistics & Distribution"),
    ("quality_management", "Quality Management"),
    ("lean_six_sigma", "Lean & Six Sigma"),
    ("change_management", "Change Management"),
    ("business_intelligence", "Business Intelligence"),

    # Sales & Marketing
    ("marketing", "Marketing & Sales"),
    ("digital_marketing", "Digital Marketing"),
    ("seo_sem", "SEO & SEM"),
    ("social_media", "Social Media & Influencer Marketing"),
    ("brand_management", "Brand Management"),
    ("advertising", "Advertising"),
    ("ecommerce", "E-commerce"),
    ("public_relations", "Public Relations"),
    ("content_marketing", "Content Marketing"),
    ("email_marketing", "Email Marketing"),
    ("market_research", "Market Research"),
    ("customer_success", "Customer Success"),
    ("sales_engineering", "Sales Engineering"),
    ("account_management", "Account Management"),
    ("channel_partner", "Channel & Partner Management"),
    ("affiliate_marketing", "Affiliate Marketing"),
    ("conversion_optimization", "Conversion Rate Optimization"),

    # Education & Academia
    ("education", "Education & Training"),
    ("k12_education", "K–12 Education"),
    ("higher_ed", "Higher Education & Academia"),
    ("edtech", "Education Technology"),
    ("adult_education", "Adult & Continuing Education"),
    ("instructional_design", "Instructional Design & Curriculum Development"),
    ("special_education", "Special Education"),
    ("early_childhood", "Early Childhood Education"),
    ("educational_administration", "Educational Administration"),
    ("student_services", "Student Affairs & Services"),
    ("library_science", "Library & Information Science"),
    ("corporate_training", "Corporate Training & Development"),
    ("vocational_education", "Vocational & Technical Education"),
    ("education_consulting", "Education Consulting"),
    ("tutoring", "Tutoring & Test Prep"),

    # Engineering & Manufacturing
    ("engineering", "Engineering"),
    ("mechanical_engineering", "Mechanical Engineering"),
    ("electrical_engineering", "Electrical Engineering"),
    ("civil_engineering", "Civil & Structural Engineering"),
    ("chemical_engineering", "Chemical Engineering"),
    ("biomedical_engineering", "Biomedical Engineering"),
    ("manufacturing", "Manufacturing & Production"),
    ("industrial_engineering", "Industrial Engineering"),
    ("aerospace", "Aerospace Engineering"),
    ("environmental_engineering", "Environmental Engineering"),
    ("materials_engineering", "Materials Engineering"),
    ("petroleum_engineering", "Petroleum Engineering"),
    ("nuclear_engineering", "Nuclear Engineering"),
    ("marine_engineering", "Marine Engineering"),
    ("mining_engineering", "Mining Engineering"),
    ("systems_engineering", "Systems Engineering"),
    ("safety_engineering", "Safety Engineering"),
    ("quality_engineering", "Quality Engineering"),
    ("process_engineering", "Process Engineering"),
    ("packaging_engineering", "Packaging Engineering"),
    ("reliability_engineering", "Reliability Engineering"),

    # Creative & Arts
    ("design", "Design & Creative"),
    ("graphic_design", "Graphic Design"),
    ("ux_ui", "UX/UI Design"),
    ("multimedia", "Multimedia & Animation"),
    ("game_design", "Game Design & Development"),
    ("fashion", "Fashion & Textile Design"),
    ("interior_design", "Interior Design"),
    ("photography", "Photography & Videography"),
    ("writing", "Writing & Content Creation"),
    ("performing_arts", "Performing Arts"),
    ("fine_arts", "Fine Arts"),
    ("music_production", "Music Production & Audio Engineering"),
    ("film_production", "Film & Video Production"),
    ("architecture", "Architecture"),
    ("landscape_architecture", "Landscape Architecture"),
    ("industrial_design", "Industrial Design"),
    ("art_therapy", "Art Therapy"),
    ("museum_curation", "Museum & Gallery Management"),
    ("arts_administration", "Arts Administration"),
    ("crafts_artisan", "Crafts & Artisan Work"),
    ("tattoo_artist", "Tattoo & Body Art"),
    ("makeup_artistry", "Makeup & Beauty Artistry"),

    # Law & Government
    ("legal", "Legal & Law"),
    ("law_enforcement", "Law Enforcement"),
    ("public_policy", "Public Policy"),
    ("government", "Government & Public Administration"),
    ("international_relations", "International Relations"),
    ("military", "Military & Defense"),
    ("paralegal", "Paralegal Services"),
    ("court_services", "Court Services"),
    ("corrections", "Corrections & Rehabilitation"),
    ("immigration_law", "Immigration Services"),
    ("regulatory_affairs", "Regulatory Affairs"),
    ("political_science", "Political Science & Campaigns"),
    ("diplomatic_services", "Diplomatic Services"),
    ("homeland_security", "Homeland Security"),
    ("firefighting", "Fire & Emergency Services"),
    ("private_investigation", "Private Investigation"),
    ("legal_technology", "Legal Technology"),

    # Sciences & Environment
    ("natural_sciences", "Natural & Physical Sciences"),
    ("life_sciences", "Life Sciences & Biology"),
    ("environmental", "Environmental Science & Sustainability"),
    ("geosciences", "Geology & Earth Sciences"),
    ("physics", "Physics & Astronomy"),
    ("chemistry", "Chemistry"),
    ("math_stats", "Mathematics & Statistics"),
    ("agriculture", "Agriculture & Food Science"),
    ("marine_science", "Marine & Ocean Sciences"),
    ("atmospheric_science", "Atmospheric & Climate Sciences"),
    ("forensic_science", "Forensic Science"),
    ("conservation", "Wildlife & Conservation"),
    ("forestry", "Forestry & Natural Resources"),
    ("biotechnology", "Biotechnology"),
    ("renewable_energy", "Renewable Energy"),
    ("water_resources", "Water Resources Management"),
    ("soil_science", "Soil & Agricultural Sciences"),
    ("meteorology", "Meteorology"),
    ("seismology", "Seismology"),
    ("archaeology", "Archaeology"),
    ("anthropology", "Anthropology"),
    ("psychology_research", "Research Psychology"),
    ("sociology", "Sociology"),

    # Media & Communication
    ("media", "Media & Communication"),
    ("journalism", "Journalism"),
    ("broadcasting", "Broadcasting & Radio"),
    ("film_tv", "Film & Television"),
    ("publishing", "Publishing & Editorial"),
    ("technical_writing", "Technical Writing"),
    ("copywriting", "Copywriting"),
    ("translation", "Translation & Interpretation"),
    ("podcasting", "Podcasting"),
    ("streaming", "Live Streaming & Content Creation"),
    ("documentary", "Documentary Production"),
    ("communications", "Corporate Communications"),
    ("media_planning", "Media Planning & Buying"),

    # Hospitality & Service
    ("hospitality", "Hospitality & Tourism"),
    ("food_service", "Food & Beverage Service"),
    ("event_management", "Event Planning & Management"),
    ("retail", "Retail & Customer Service"),
    ("transportation", "Transportation & Logistics"),
    ("travel_planning", "Travel Planning & Tourism"),
    ("hotel_management", "Hotel & Resort Management"),
    ("cruise_industry", "Cruise Industry"),
    ("airline_industry", "Airline Industry"),
    ("concierge", "Concierge & Guest Services"),
    ("catering", "Catering Services"),
    ("casino_gaming", "Casino & Gaming"),
    ("spa_wellness", "Spa & Wellness Services"),
    ("tour_guide", "Tour Guide Services"),

    # Trades & Vocational Fields
    ("construction", "Construction & Skilled Trades"),
    ("automotive", "Automotive Technology"),
    ("electrician", "Electrical & Wiring"),
    ("plumbing", "Plumbing & HVAC"),
    ("mechanic", "Mechanical & Equipment Repair"),
    ("welding", "Welding & Fabrication"),
    ("carpentry", "Carpentry & Woodworking"),
    ("masonry", "Masonry & Stonework"),
    ("roofing", "Roofing"),
    ("painting", "Painting & Decorating"),
    ("flooring", "Flooring Installation"),
    ("appliance_repair", "Appliance Repair"),
    ("locksmith", "Locksmith Services"),
    ("pest_control", "Pest Control"),
    ("landscaping", "Landscaping & Groundskeeping"),
    ("pool_maintenance", "Pool & Spa Maintenance"),
    ("heavy_equipment", "Heavy Equipment Operation"),
    ("crane_operator", "Crane Operation"),
    ("elevator_technician", "Elevator & Escalator Technology"),
    ("telecommunications_tech", "Telecommunications Installation"),

    # Personal Care & Beauty
    ("beauty_personal_care", "Beauty & Personal Care"),
    ("cosmetology", "Cosmetology & Hair Styling"),
    ("esthetics", "Esthetics & Skincare"),
    ("nail_technology", "Nail Technology"),
    ("massage_therapy", "Massage Therapy"),
    ("personal_training", "Personal Training & Fitness"),
    ("life_coaching", "Life & Career Coaching"),
    ("childcare", "Childcare & Nanny Services"),
    ("elder_care", "Elder Care Services"),
    ("pet_services", "Pet Care & Services"),

    # Security & Safety
    ("security", "Security Services"),
    ("private_security", "Private Security"),
    ("cybersecurity_physical", "Physical Security"),
    ("loss_prevention", "Loss Prevention"),
    ("emergency_management", "Emergency Management"),
    ("occupational_safety", "Occupational Health & Safety"),
    ("environmental_safety", "Environmental Health & Safety"),

    # Research & Development
    ("research_development", "Research & Development"),
    ("clinical_research", "Clinical Research"),
    ("market_research_specialist", "Market Research Specialist"),
    ("product_development", "Product Development"),
    ("innovation_management", "Innovation Management"),
    ("patent_analysis", "Patent & IP Analysis"),

    # Food & Culinary
    ("culinary", "Culinary Arts"),
    ("chef", "Professional Cooking"),
    ("baking_pastry", "Baking & Pastry Arts"),
    ("food_science", "Food Science & Technology"),
    ("nutrition_specialist", "Nutrition Specialist"),
    ("sommelier", "Wine & Beverage Specialist"),
    ("food_photography", "Food Photography & Styling"),
    ("restaurant_management", "Restaurant Management"),
    ("food_safety", "Food Safety & Inspection"),

    # Transportation & Logistics
    ("aviation", "Aviation & Pilot Services"),
    ("maritime", "Maritime & Shipping"),
    ("trucking", "Trucking & Commercial Driving"),
    ("public_transit", "Public Transportation"),
    ("warehouse", "Warehouse & Distribution"),
    ("supply_chain", "Supply Chain Management"),
    ("freight", "Freight & Cargo Services"),
    ("customs_trade", "Customs & International Trade"),

    # Energy & Utilities
    ("energy", "Energy Sector"),
    ("oil_gas", "Oil & Gas Industry"),
    ("renewable_energy_tech", "Renewable Energy Technology"),
    ("utilities", "Utilities & Power Generation"),
    ("nuclear_power", "Nuclear Power"),
    ("solar_energy", "Solar Energy"),
    ("wind_energy", "Wind Energy"),
    ("energy_efficiency", "Energy Efficiency"),

    # Real Estate & Property
    ("real_estate_agent", "Real Estate Sales"),
    ("property_management", "Property Management"),
    ("real_estate_appraisal", "Real Estate Appraisal"),
    ("real_estate_development", "Real Estate Development"),
    ("facility_management", "Facility Management"),
    ("building_inspection", "Building Inspection"),
    ("property_maintenance", "Property Maintenance"),

    # Sports & Recreation
    ("sports", "Sports & Athletics"),
    ("sports_coaching", "Sports Coaching"),
    ("sports_management", "Sports Management"),
    ("recreation", "Recreation & Leisure Services"),
    ("outdoor_recreation", "Outdoor Recreation"),
    ("fitness_instruction", "Fitness Instruction"),
    ("sports_medicine", "Sports Medicine"),
    ("sports_journalism", "Sports Journalism"),
    ("sports_marketing", "Sports Marketing"),

    # Miscellaneous & Emerging Fields
    ("nonprofit", "Nonprofit & Social Work"),
    ("religious", "Religious & Ministry Work"),
    ("other", "Other / Miscellaneous"),
    ("social_services", "Social Services"),
    ("community_development", "Community Development"),
    ("disability_services", "Disability Services"),
    ("addiction_counseling", "Addiction & Recovery Services"),
    ("family_services", "Family & Child Services"),
    ("refugee_services", "Refugee & Immigration Services"),
    ("crowdfunding", "Crowdfunding & Fundraising"),
    ("sustainability_consulting", "Sustainability Consulting"),
    ("user_research", "User Research"),
    ("voice_acting", "Voice Acting & Narration"),
    ("drone_services", "Drone & UAV Services"),
    ("3d_printing", "3D Printing & Additive Manufacturing"),
    ("virtual_reality", "Virtual & Augmented Reality"),
    ("esports", "Esports & Gaming"),
    ("influencer", "Social Media Influencing"),
    ("online_tutoring", "Online Education & Tutoring"),
    ("freelance_gig", "Freelance & Gig Economy"),
    ("consulting_independent", "Independent Consulting"),
    ("coaching_mentoring", "Professional Coaching & Mentoring"),
]