LEVEL_CHOICES = [
        ("entry_level", "Entry Level"),
        ("intern", "Intern"),
        ("trainee", "Trainee"),
        ("associate", "Associate"),
        ("junior", "Junior"),
        ("beginner", "Beginner"),
        ("mid_level", "Mid Level"),
        ("intermediate", "Intermediate"),
        ("experienced", "Experienced"),
        ("senior", "Senior"),
        ("lead", "Lead"),
        ("principal", "Principal"),
        ("staff", "Staff"),
        ("senior_staff", "Senior Staff"),
        ("architect", "Architect"),
        ("senior_architect", "Senior Architect"),
        ("team_lead", "Team Lead"),
        ("tech_lead", "Tech Lead"),
        ("manager", "Manager"),
        ("senior_manager", "Senior Manager"),
        ("director", "Director"),
        ("senior_director", "Senior Director"),
        ("vp", "Vice President"),
        ("svp", "Senior Vice President"),
        ("cto", "Chief Technology Officer"),
        ("ceo", "Chief Executive Officer"),
        ("consultant", "Consultant"),
        ("senior_consultant", "Senior Consultant"),
        ("specialist", "Specialist"),
        ("expert", "Expert"),
        ("freelancer", "Freelancer"),
        ("contractor", "Contractor"),
    ]